---
name: File-BSED
version: 0.67
author:
  - 'Ask Solem <ASKSH@cpan.org>'
abstract: Search/Replace in Binary Files.
license: perl
resources:
  HomePage: http://search.cpan.org/dist/File-BSED/
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-BSED
  license: http://dev.perl.org/licenses/
requires:
  ExtUtils::ParseXS: 0
  Getopt::LL: 0
build_requires:
  Test::Simple: 0.42
dynamic_config: 1
provides:
  File::BSED:
    file: lib/File/BSED.pm
    version: 0.67
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: Module
