---
name: File-BSED
version: 0.3
author:
  - 'Ask Solem <ASKSH@cpan.org>'
abstract: Search/Replace in Binary Files.
license: gpl
resources:
  HomePage: http://search.cpan.org/~asksh/File-BSED-0.3/
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-BSED
  license: http://www.opensource.org/licenses/gpl-license.php
requires:
  ExtUtils::ParseXS: 0
  Getopt::LL: 0
build_requires:
  Test::Simple: 0.42
dynamic_config: 1
no_index:
    directory:
        - inc
        - t
provides:
  File::BSED:
    file: lib/File/BSED.pm
    version: 0.3
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: Module
